source 'http://rubygems.org'

gem 'urbanopt-scenario', '0.3.0'

gem 'urbanopt-reopt', '0.3.0'

gem 'urbanopt-geojson', '0.3.1'

gem 'openstudio-standards', '0.2.11' # doesn't work in 0.2.8?

# simplecov has an unneccesary dependency on native json gem, use fork that does not require this
# gem 'simplecov', github: 'NREL/simplecov'
# Use the regular one because the NREL fork isn't updated with a tag that's compatible with urbanopt-geojson...
gem 'simplecov'

gem 'certified'

gem 'daru', '>=0.2.2'
gem 'daru-view', git: 'https://github.com/SciRuby/daru-view'
gem 'ffi-rzmq'
gem 'iruby'
